security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13 #cost is 13 by default, just so you know why and how to set it

    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        secured_area:
            pattern: ^/

            anonymous: true

            form_login:
                check_path: user_login
                login_path: user_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /

            logout:
                # The route name the user can go to in order to logout
                path: user_logout
                # The name of the route to redirect to after logging out
                target: homepage

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/uzivatel/*, roles: IS_AUTHENTICATED_FULLY }
