# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.controller.category_controller:
    class: AppBundle\Controller\CategoryController
    autowire: true

  app.controller.homepage_controller:
    class: AppBundle\Controller\HomepageController
    autowire: true

  app.controller.product_controller:
    class: AppBundle\Controller\ProductController
    autowire: true

  app.facade.category_facade:
    class: AppBundle\Facade\CategoryFacade
    autowire: true

  app.facade.product_facade:
    class: AppBundle\Facade\ProductFacade
    autowire: true

  app.repository.category_repository:
    class: AppBundle\Repository\CategoryRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Category']

  app.repository.product_repository:
    class: AppBundle\Repository\ProductRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Product']
